from pydantic import BaseModel

class get_data(BaseModel):
    Age: float
    Gender: str
    Temperature: float
    Humidity: float
    Wind_Speed: float
    nausea: float
    joint_pain: float
    abdominal_pain: float
    high_fever: float
    chills: float
    fatigue: float
    runny_nose: float
    pain_behind_the_eyes: float
    dizziness: float
    headache: float
    chest_pain: float
    vomiting: float
    cough: float
    hiv_aids: float
    nasal_polyps: float
    asthma: float
    high_blood_pressure: float
    severe_headache: float
    weakness: float
    trouble_seeing: float
    fever: float
    body_aches: float
    sore_throat: float
    sneezing: float
    diarrhea: float
    rapid_breathing: float
    rapid_heart_rate: float
    pain_behind_eyes: float
    swollen_glands: float
    rashes: float
    sinus_headache: float
    facial_pain: float
    shortness_of_breath: float
    reduced_smell_and_taste: float
    skin_irritation: float
    itchiness: float
    throbbing_headache: float
    confusion: float
    back_pain: float
    knee_ache: float
